# Generated by Django 4.1.7 on 2023-05-18 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airways_arrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Havayolu adı')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
            ],
        ),
        migrations.CreateModel(
            name='Airways_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Havayolu şirketi')),
                ('brand', models.CharField(max_length=50, verbose_name='Markası')),
            ],
        ),
        migrations.CreateModel(
            name='Airways_depture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Havayolu adı')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Başlık')),
                ('text', models.CharField(max_length=50, null=True, verbose_name='Açıklama')),
                ('price', models.FloatField(max_length=50, null=True, verbose_name='Fiyat')),
                ('time', models.DateField(verbose_name='Zaman')),
                ('arrive_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.airways_arrive', verbose_name='Varış yeri')),
                ('depeture_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.airways_depture', verbose_name='Kalkış yeri')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.airways_company', verbose_name='uçuş şirketi')),
            ],
        ),
    ]
