# Generated by Django 4.1.7 on 2023-05-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_flight_adult_flight_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='variş_date',
            field=models.DateField(null=True, verbose_name='varış Zamanı'),
        ),
    ]
